# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set Node.js 16.x
      uses: actions/setup-node@main
      with:
        version: 16.x
    - name: instal dep fe
      run: npm ci
      working-directory: ./frontend

    - name: instal dep be
      run: npm ci
      working-directory: ./backend

    - name: build
      run: npm run build --if-present
      working-directory: ./frontend

    - name: copy build
      run:  cp -r frontend/build/* ../backend/app/views/

    - name:  deploy
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd /var/lib/docker/volumes/react-crud-learn_react-storage/_data/backend/app/views/ && tar -xf build.tar && cp -rf build/* . && rm -rf build build.tar
        host: ${{ secrets.HOST-DEV }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
 
    - name: finishing deploy
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd /var/lib/docker/volumes/react-crud-learn_react-storage/_data/ && cp -rf backend/* . && rm -rf backend
        host: ${{ secrets.HOST-DEV }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: restart container
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd /home/owel/dev/react-crud-learn && docker-compose restart
        host: ${{ secrets.HOST-DEV }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}


 
