# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set Node.js 16.x
      uses: actions/setup-node@main
      with:
        version: 16.x
    - name: instal ci
      run: npm ci
      working-directory: ./frontend
    - name: build
      run: npm run build --if-present
      working-directory: ./frontend
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: scp # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: ${{ secrets.CONFIG }} # ssh_config; optional
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
    - name: rsync over ssh
      run: rsync ./frontend/build/* root@34.101.187.18:/var/lib/docker/volumes/react-storage/_data/
    
 
